/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsSlugRouteImport } from './routes/locations/$slug'
import { Route as MerchIndexRouteImport } from './routes/merch/index'
import { Route as MerchCheckoutRouteImport } from './routes/merch/checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchIndexRoute = MerchIndexRouteImport.update({
  id: '/merch/',
  path: '/merch/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchCheckoutRoute = MerchCheckoutRouteImport.update({
  id: '/merch/checkout',
  path: '/merch/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/fitness': typeof FitnessRoute
  '/memberships': typeof MembershipsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trainers': typeof TrainersRoute
  '/events/$slug': typeof EventsSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/merch/checkout': typeof MerchCheckoutRoute
  '/events/': typeof EventsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/merch/': typeof MerchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/fitness': typeof FitnessRoute
  '/memberships': typeof MembershipsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trainers': typeof TrainersRoute
  '/events/$slug': typeof EventsSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/merch/checkout': typeof MerchCheckoutRoute
  '/events': typeof EventsIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/merch': typeof MerchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/fitness': typeof FitnessRoute
  '/memberships': typeof MembershipsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trainers': typeof TrainersRoute
  '/events/$slug': typeof EventsSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/merch/checkout': typeof MerchCheckoutRoute
  '/events/': typeof EventsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/merch/': typeof MerchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/fitness'
    | '/memberships'
    | '/privacy'
    | '/terms'
    | '/trainers'
    | '/events/$slug'
    | '/locations/$slug'
    | '/merch/checkout'
    | '/events/'
    | '/locations/'
    | '/merch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/fitness'
    | '/memberships'
    | '/privacy'
    | '/terms'
    | '/trainers'
    | '/events/$slug'
    | '/locations/$slug'
    | '/merch/checkout'
    | '/events'
    | '/locations'
    | '/merch'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply'
    | '/fitness'
    | '/memberships'
    | '/privacy'
    | '/terms'
    | '/trainers'
    | '/events/$slug'
    | '/locations/$slug'
    | '/merch/checkout'
    | '/events/'
    | '/locations/'
    | '/merch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  FitnessRoute: typeof FitnessRoute
  MembershipsRoute: typeof MembershipsRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TrainersRoute: typeof TrainersRoute
  EventsSlugRoute: typeof EventsSlugRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  MerchCheckoutRoute: typeof MerchCheckoutRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  MerchIndexRoute: typeof MerchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch/': {
      id: '/merch/'
      path: '/merch'
      fullPath: '/merch/'
      preLoaderRoute: typeof MerchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch/checkout': {
      id: '/merch/checkout'
      path: '/merch/checkout'
      fullPath: '/merch/checkout'
      preLoaderRoute: typeof MerchCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  FitnessRoute: FitnessRoute,
  MembershipsRoute: MembershipsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TrainersRoute: TrainersRoute,
  EventsSlugRoute: EventsSlugRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  MerchCheckoutRoute: MerchCheckoutRoute,
  EventsIndexRoute: EventsIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  MerchIndexRoute: MerchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
